### ISSUE TITLE
V32 Steam Logo is too dark against the background

### ISSUE THREAD

**Issue by bornagainpenguin** [lehcimcramtrebor/es-theme-batocer-club-reloaded#1]
With the new addition of Steam to the system, there is now a logo which can be selected to select various installed Steam games.  Unfortunately the logo shows up as black against a dark backdrop.  See attached [image](https://i.imgur.com/3P3m30A.jpg).  It might be better to either color the logo lighter or to simply outline it with white such as the PS1 logo is.

Enjoying the awesome theme, thanks for making it!

**Comment by lehcimcramtrebor** [comment]
I have just created clear-logo.
