### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by H2SO4JB** [lehcimcramtrebor/es-theme-batocer-club-reloaded#2]
Hi lehcimcramtrebor,

Thank you for this wonderful theme. Nice work!
I have done a Swedish translation of all the strings in this theme, but I'm not
sure how to upload it to Github. Are you interested in implementing it in your theme?
If so, I attach the file here. Thanks in advance.
[lang-sv.zip](https://github.com/lehcimcramtrebor/es-theme-batocer-club-reloaded/files/7595663/lang-sv.zip)
..

**Comment by lehcimcramtrebor** [comment]
Hi, thank you for translation, I’ve just added your file from my iPhone.. I will credite you in theme file when I will go back at home.

**Comment by H2SO4JB** [comment]
Great, thanks! 👍🏻
My real name is Jonas Bohdén if you need it. You can contact me here if
there is anything more Swedish translation I can help you with in the future.

**Comment by lehcimcramtrebor** [comment]
Ok, thank you Jonas.
